### ISSUE TITLE
Filter out embedded videos

### ISSUE THREAD

**Issue by CP1832** [igorbrigadir/twitter-advanced-search#30]
Hi guys:

Is there any way to filter out embedded videos (shared using <url>/video/1) from uploaded videos? I have tried both filter:consumer_videos and filter:videos but both embedded and uploaded videos show up on the search results.

Thanks in advance.

**Comment by igorbrigadir** [comment]
Do you have a link to a search example with tweets that shouldn't be there?

**Comment by CP1832** [comment]
Hi Igor:

I am not saying that the search isn't working. For instance, this search (https://twitter.com/search?q=from%3Aespn%20filter%3Aconsumer_video%20since%3A2021-05-25%20until%3A2021-05-27&src=typed_query&f=live) shows the following result (https://twitter.com/espn/status/1397360602557947907), which has an embedded video (https://twitter.com/NBA/status/1397359439078989825/video/1). Is there any way to filter out that tweet from, for example, this (https://twitter.com/espn/status/1397421924595027970), which has a non embedded video in it?

**Comment by tibor** [comment]
Hi @CP1832,

you can do that for a specific account by combining filters like so: `from:cp1832 filter:native_video url:twitter.com/cp1832` to find all native videos uploaded and tweeted by cp1832 or `from:cp1832 filter:native_video -url:twitter.com/cp1832` for all embedded videos that cp1832 tweeted.

However, if you're looking for a search to get this working without specifying an account, that would only work with a programmatic approach, i.e. using the API and filtering the results with custom code.

**Comment by CP1832** [comment]
Thanks @tibor, I have been trying it and it seems to work, but I can't get it to work with account names containing underscores, for example, from:EU_ENV filter:native_video -url:https://twitter.com/EU_ENV Does the underscore need to be escaped somehow?

**Comment by igorbrigadir** [comment]
That looks like it works for me: https://twitter.com/search?q=from%3AEU_ENV%20filter%3Anative_video%20-url%3Ahttps%3A%2F%2Ftwitter.com%2FEU_ENV&src=typed_query&f=live underscores don't need to be escaped (but a dash `-` in a url does, it's replaced with `_`)

**Comment by CP1832** [comment]
But it's not working, I can see still see the native videos uploaded by EU_ENV in the search when I wanted to filter them out and only see their embedded videos.
![2021-06-18 18_30_51](https://user-images.githubusercontent.com/5098810/122617822-5917be00-d063-11eb-8057-ab7620119d41.jpg)

**Comment by igorbrigadir** [comment]
oh! right - i think i get what you mean now?

To get videos that are posted by an account, but come from different accounts, like https://twitter.com/espn/status/1397360602557947907 you can use `url:` operator:

https://twitter.com/search?q=from%3Aespn%20url%3Atwitter.com%20url%3Avideo%20-url%3Atwitter.com%2Fespn&src=typed_query&f=live

I don't think it works for EU_ENV because that account doesn't have videos like that.

Also `url:` searches can be quite flaky so it's not guaranteed to work every time.

**Comment by CP1832** [comment]
I found another example. For instance, https://twitter.com/espn_macmahon/status/1102040867026714624 has a native video from another account (https://twitter.com/utahjazz/status/1102039385954893824/video/1) and the search from:espn_macmahon -url:twitter.com/espn_macmahon filter:native_video doesn't work either, it shows all the native videos from that account. I guess the url: search doesn't work correctly when there is an underscore, because it works quite well in the other cases...

**Comment by igorbrigadir** [comment]
yeah that seems like a pattern alright - good to know!

**Comment by tibor** [comment]
Yes, I had that problem with other searches as well. I guess it's because Twitter escapes dashes in URLs with underscores and they're reversing the process somewhere in their code, which makes regular underscores look like dashes.

However, you should be able to get to your aim by using a simple algorithm that filters all unwanted URLs. Take a look at Twint for python, you don't even need a paid API access for that.
