### ISSUE TITLE
scrape tweet with place id not equal to null

### ISSUE THREAD

**Issue by husky0723** [igorbrigadir/twitter-advanced-search#31]
Hi, sry if this is a dumb question. i'm new to this library. 

Is there anyway to scrape tweets with place id not equal to null

Thanks in advance

**Comment by igorbrigadir** [comment]
Sure - for getting tweet data, I recommend twarc https://github.com/DocNow/twarc `twarc` command can use v1.1 API and `twarc2` command can use v2 Search APIs. You'll get `place_id` and related metadata depending on what queries you run: https://twarc-project.readthedocs.io/en/latest/

This repository is for the Web interface / Tweet Deck Advanced Search only, so not everything here will work in the API - this repository is purely to list all the options for building queries on the web interface.

**Comment by husky0723** [comment]
Is the twarc have limits for free user?

**Comment by igorbrigadir** [comment]
Twarc limits are the Twitter API limits, yes: https://developer.twitter.com/en/docs/rate-limits

**Comment by husky0723** [comment]
is there a way to bypass it? i'm just a student and need to scrape for academic project. Another question how do i get the place ID of that country?

Sry for asking so much question

**Comment by igorbrigadir** [comment]
If you're a student, you may be able to get your professor or course coordinator to get Academic Access: https://twarc-project.readthedocs.io/en/latest/twitter-developer-access/

Otherwise, there is no way to bypass the rate limits on the API.

Place IDs can be queried with https://developer.twitter.com/en/docs/twitter-api/v1/geo/places-near-location/api-reference/get-geo-search 

and generally for any questions like that about the API https://twittercommunity.com/ is the place to go!
