### ISSUE TITLE
until

### ISSUE THREAD

**Issue by alxzvfx** [igorbrigadir/twitter-advanced-search#40]
(from:alxzvfx) since:2022-07-22 until:2022-07-22 filter:nativeretweets 
this search isnt working. when i get rid of the until it works but i need until to see my retweets from a specific date

**Comment by igorbrigadir** [comment]
> since:2022-07-22 until:2022-07-22

`since:` is on or after (inclusive) a specified date, but `until:` is Before (NOT inclusive) the specified date. So you probably want:

```
(from:alxzvfx) since:2022-07-22 until:2022-07-23 filter:nativeretweets
```

To get everything between UTC `2022-07-22 00:00:00` to `2022-07-22 23:59:59`

Make sure to use "Latest" and not "Top".

Also, sometimes search will fail, and there's nothing you can do - so specifying only `until:` allows you to scroll backwards, and you can iteratively change the query. going back in time as far as you need.

Unfortunately, the web search on twitter isn't 100% reliable and consistent.

**Comment by alxzvfx** [comment]
(from:alxzvfx) since:2022-07-22 until:2022-07-23 filter:nativeretweets

this still doesn't work also just adding until doesn't work so is there no way to view my old retweets?
________________________________

**Comment by igorbrigadir** [comment]
> is there no way to view my old retweets?

I think if the search keeps failing, the best thing to do is request your Archive and get them that way - https://twitter.com/settings/download_your_data
