### ISSUE TITLE
Appears filter:follows cant be negated (add note?)

### ISSUE THREAD

**Issue by koobs** [igorbrigadir/twitter-advanced-search#45]
## Summary

`filter:follows` cannot be negated with either `-` or `exclude`. Add note to `Users > filter:follows` class table entry and/or `Building Queries` section accordingly.

## Description

Documentation currently states:

`filter:follows 	Only from accounts you follow`

and

`Any "filter:type" can also be negated using the "-" symbol. exclude:links is the same as -filter:links`

However, it appears that neither `<term> -filter:follows` nor `<keyword> exclude:follows` are "honoured".

## Additional Notes

Other `filter:<class>`'s may also be affected (non-negatable), if they haven't already been verified to work. They're likely all worth testing. 

With that in mind, one may also consider adding an new column in the main table: 'Last Verified' or 'Verified Working' with an ISO-8601 datestamp for the last time correct function was checked.

## Reproduction Tests

* `<term> -filter:follows` and `<keyword> exclude:follows`
  * Web 
  * iPhone
  * For: Top / Latest / People / Photos Videos
* `<term> -filter:follows` returns the same results as non-negated `<term> filter:follows`
* `<keyword> exclude:follows` returns no results, resumably because `exclude:follows` is not matched in content

**Comment by igorbrigadir** [comment]
Yeah, would be a good thing to have alright - i've added a note about not being able to negate `filter:follows`

As for the last checked, i think an appropriate place to put that is into the alt text of the image / link to the search. I'd rather not add an extra column for readability, and since a few of these are flaky, it's better to link to an example anyway.

But thanks again!

**Comment by koobs** [comment]
Thanks so much for this documentation :) shame follows can't be negated :(
